CHANNEL_NAME = 'wecom'
DEFAULT_WEBSOCKET_URL = 'wss://openws.work.weixin.qq.com'

ENV_BOT_ID = 'WECOM_BOT_ID'
ENV_BOT_SECRET = 'WECOM_BOT_SECRET'
ENV_CALLBACK_TOKEN = 'WECOM_CALLBACK_TOKEN'
ENV_ENCODING_AES_KEY = 'WECOM_ENCODING_AES_KEY'
ENV_RECEIVE_ID = 'WECOM_RECEIVE_ID'
ENV_WEBSOCKET_URL = 'WECOM_WEBSOCKET_URL'
